package br.com.mgr.corba.lib.OperacoesApp;

/**
* OperacoesApp/OperacoesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaOperacoes.idl
* Segunda-feira, 8 de Março de 2021 09h58min05s BRT
*/

abstract public class OperacoesHelper
{
  private static String  _id = "IDL:OperacoesApp/Operacoes:1.0";

  public static void insert (org.omg.CORBA.Any a, br.com.mgr.corba.lib.OperacoesApp.Operacoes that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.com.mgr.corba.lib.OperacoesApp.Operacoes extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.com.mgr.corba.lib.OperacoesApp.OperacoesHelper.id (), "Operacoes");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.com.mgr.corba.lib.OperacoesApp.Operacoes read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperacoesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.com.mgr.corba.lib.OperacoesApp.Operacoes value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.com.mgr.corba.lib.OperacoesApp.Operacoes narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.mgr.corba.lib.OperacoesApp.Operacoes)
      return (br.com.mgr.corba.lib.OperacoesApp.Operacoes)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.mgr.corba.lib.OperacoesApp._OperacoesStub stub = new br.com.mgr.corba.lib.OperacoesApp._OperacoesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.com.mgr.corba.lib.OperacoesApp.Operacoes unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.com.mgr.corba.lib.OperacoesApp.Operacoes)
      return (br.com.mgr.corba.lib.OperacoesApp.Operacoes)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.com.mgr.corba.lib.OperacoesApp._OperacoesStub stub = new br.com.mgr.corba.lib.OperacoesApp._OperacoesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
