package br.com.mgr.corba.lib.OperacoesApp;


/**
* OperacoesApp/Operacoes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaOperacoes.idl
* Segunda-feira, 8 de Março de 2021 09h58min05s BRT
*/

public interface Operacoes extends OperacoesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operacoes
