package br.com.mgr.corba.lib.OperacoesApp;


/**
* OperacoesApp/OperacoesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaOperacoes.idl
* Segunda-feira, 8 de Março de 2021 09h58min05s BRT
*/

public final class OperacoesHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.mgr.corba.lib.OperacoesApp.Operacoes value = null;

  public OperacoesHolder ()
  {
  }

  public OperacoesHolder (br.com.mgr.corba.lib.OperacoesApp.Operacoes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.mgr.corba.lib.OperacoesApp.OperacoesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.mgr.corba.lib.OperacoesApp.OperacoesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.mgr.corba.lib.OperacoesApp.OperacoesHelper.type ();
  }

}
